# backend/test_pdf_generation.py - Run this to test PDF generation locally
# Usage: python test_pdf_generation.py

import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'backend.settings')
django.setup()

from django.contrib.auth import get_user_model
from datetime import datetime, timedelta
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate
import io

User = get_user_model()

print("🧪 Testing PDF Generation System...")
print("=" * 70)

# Test 1: Check ReportLab Installation
print("\n1️⃣ Testing ReportLab Installation...")
try:
    from reportlab.lib import colors
    from reportlab.lib.units import inch
    from reportlab.platypus import Table, TableStyle, Paragraph, Spacer
    from reportlab.lib.styles import getSampleStyleSheet
    print("✅ ReportLab installed correctly")
except ImportError as e:
    print(f"❌ ReportLab import failed: {e}")
    print("   Run: pip install reportlab")
    exit(1)

# Test 2: Generate Simple PDF
print("\n2️⃣ Testing PDF Generation...")
try:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    
    styles = getSampleStyleSheet()
    story = [
        Paragraph("Test PDF Generation", styles['Title']),
        Spacer(1, 0.2*inch),
        Paragraph("This is a test PDF generated by AdVision", styles['Normal']),
    ]
    
    doc.build(story)
    buffer.seek(0)
    
    pdf_size = len(buffer.getvalue())
    print(f"✅ PDF generated successfully ({pdf_size} bytes)")
    
    # Save test PDF
    with open('test_report.pdf', 'wb') as f:
        f.write(buffer.getvalue())
    print("✅ Saved to: test_report.pdf")
    
except Exception as e:
    print(f"❌ PDF generation failed: {e}")
    exit(1)

# Test 3: Check User Exists
print("\n3️⃣ Testing Database Access...")
try:
    demo_user = User.objects.filter(email='demo@advision.com').first()
    if demo_user:
        print(f"✅ Found demo user: {demo_user.email}")
    else:
        print("⚠️  No demo user found. Run: python create_demo_data.py")
except Exception as e:
    print(f"❌ Database error: {e}")

# Test 4: Test View Import
print("\n4️⃣ Testing View Imports...")
try:
    from core.views import GenerateWeeklyReportPDFView
    print("✅ GenerateWeeklyReportPDFView imported successfully")
except ImportError as e:
    print(f"❌ View import failed: {e}")
    print("   Make sure you've added the new view class to views.py")

# Test 5: Test URL Configuration
print("\n5️⃣ Testing URL Configuration...")
try:
    from django.urls import resolve
    
    # Test if endpoint exists
    match = resolve('/api/reports/weekly/pdf/')
    print(f"✅ URL endpoint configured: {match.url_name}")
except Exception as e:
    print(f"⚠️  URL may not be configured: {e}")
    print("   Add to urls.py: path('reports/weekly/pdf/', ...)")

# Test 6: Full Integration Test
print("\n6️⃣ Testing Full Report Generation...")
try:
    from core.models import Campaign, DailyAnalytics, CampaignAnalyticsSummary
    from django.db.models import Sum
    
    if not demo_user:
        print("⚠️  Skipping (no demo user)")
    else:
        # Get sample data
        campaigns = Campaign.objects.filter(user=demo_user).count()
        analytics = DailyAnalytics.objects.filter(campaign__user=demo_user).count()
        
        print(f"   📊 User has {campaigns} campaigns")
        print(f"   📈 User has {analytics} analytics records")
        
        if campaigns > 0 and analytics > 0:
            print("✅ Sufficient data for report generation")
        else:
            print("⚠️  Limited data. Run: python create_demo_data.py")

except Exception as e:
    print(f"❌ Integration test failed: {e}")

# Summary
print("\n" + "=" * 70)
print("📋 TEST SUMMARY")
print("=" * 70)

print("\n✅ All critical tests passed!")
print("\n🎯 Next Steps:")
print("   1. Check test_report.pdf was created")
print("   2. Open test_report.pdf to verify it's valid")
print("   3. Start server: python manage.py runserver")
print("   4. Test in browser: http://localhost:8000/api/reports/weekly/pdf/")
print("\n💡 TIP: If any tests failed, review the error messages above")
print("=" * 70)