# Generated by Django 4.2.26 on 2025-11-22 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_image_url_imageasset_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
