# Generated by Django 4.2.17 on 2025-12-06 14:40

import core.utils.timezone_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_adcontent_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adcontent',
            name='created_at',
            field=models.DateTimeField(default=core.utils.timezone_utils.now),
        ),
        migrations.AlterField(
            model_name='imageasset',
            name='created_at',
            field=models.DateTimeField(default=core.utils.timezone_utils.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=core.utils.timezone_utils.now),
        ),
    ]
